export const ACTIVITY_UPDATE_CREATE_REQUEST = 'ACTIVITY_UPDATE_CREATE_REQUEST'
export const ACTIVITY_UPDATE_CREATE_SUCCESS = 'ACTIVITY_UPDATE_CREATE_SUCCESS'
export const ACTIVITY_UPDATE_CREATE_FAIL = 'ACTIVITY_UPDATE_CREATE_FAIL'
export const ACTIVITY_UPDATE_CREATE_RESET = 'ACTIVITY_UPDATE_CREATE_RESET'

export const ACTIVITY_UPDATE_DETAILS_REQUEST = 'ACTIVITY_UPDATE_DETAILS_REQUEST'
export const ACTIVITY_UPDATE_DETAILS_SUCCESS = 'ACTIVITY_UPDATE_DETAILS_SUCCESS'
export const ACTIVITY_UPDATE_DETAILS_FAIL = 'ACTIVITY_UPDATE_DETAILS_FAIL'
export const ACTIVITY_UPDATE_DETAILS_RESET = 'ACTIVITY_UPDATE_DETAILS_RESET'