export const SCHEDULE_FOR_SE_LIST_REQUEST = 'SCHEDULE_FOR_SE_LIST_REQUEST'
export const SCHEDULE_FOR_SE_LIST_SUCCESS = 'SCHEDULE_FOR_SE_LIST_SUCCESS'
export const SCHEDULE_FOR_SE_LIST_FAIL = 'SCHEDULE_FOR_SE_LIST_FAIL'
export const SCHEDULE_FOR_SE_LIST_RESET = 'SCHEDULE_FOR_SE_LIST_RESET'