export const ACTIVITY_RELATED_LIST_REQUEST = 'ACTIVITY_RELATED_LIST_REQUEST'
export const ACTIVITY_RELATED_LIST_SUCCESS = 'ACTIVITY_RELATED_LIST_SUCCESS'
export const ACTIVITY_RELATED_LIST_FAIL = 'ACTIVITY_RELATED_LIST_FAIL'
export const ACTIVITY_RELATED_LIST_RESET = 'ACTIVITY_RELATED_LIST_RESET'

export const ACTIVITY_RELATED_DETAILS_REQUEST = 'ACTIVITY_RELATED_DETAILS_REQUEST'
export const ACTIVITY_RELATED_DETAILS_SUCCESS = 'ACTIVITY_RELATED_DETAILS_SUCCESS'
export const ACTIVITY_RELATED_DETAILS_FAIL = 'ACTIVITY_RELATED_DETAILS_FAIL'
export const ACTIVITY_RELATED_DETAILS_RESET = 'ACTIVITY_RELATED_DETAILS_RESET'

export const ACTIVITY_RELATED_DELETE_REQUEST = 'ACTIVITY_RELATED_DELETE_REQUEST'
export const ACTIVITY_RELATED_DELETE_SUCCESS = 'ACTIVITY_RELATED_DELETE_SUCCESS'
export const ACTIVITY_RELATED_DELETE_FAIL = 'ACTIVITY_RELATED_DELETE_FAIL'



