export const ACTIVITY_RELATED_LIST_REQUEST = 'ACTIVITY_RELATED_LIST_REQUEST'
export const ACTIVITY_RELATED_LIST_SUCCESS = 'ACTIVITY_RELATED_LIST_SUCCESS'
export const ACTIVITY_RELATED_LIST_FAIL = 'ACTIVITY_RELATED_LIST_FAIL'
export const ACTIVITY_RELATED_LIST_RESET = 'ACTIVITY_RELATED_LIST_RESET'

export const ACTIVITY_RELATED_DETAILS_REQUEST = 'ACTIVITY_RELATED_DETAILS_REQUEST'
export const ACTIVITY_RELATED_DETAILS_SUCCESS = 'ACTIVITY_RELATED_DETAILS_SUCCESS'
export const ACTIVITY_RELATED_DETAILS_FAIL = 'ACTIVITY_RELATED_DETAILS_FAIL'
export const ACTIVITY_RELATED_DETAILS_RESET = 'ACTIVITY_RELATED_DETAILS_RESET'

export const ACTIVITY_RELATED_DELETE_REQUEST = 'ACTIVITY_RELATED_DELETE_REQUEST'
export const ACTIVITY_RELATED_DELETE_SUCCESS = 'ACTIVITY_RELATED_DELETE_SUCCESS'
export const ACTIVITY_RELATED_DELETE_FAIL = 'ACTIVITY_RELATED_DELETE_FAIL'

export const ACTIVITY_RELATED_CREATE_REQUEST = 'ACTIVITY_RELATED_CREATE_REQUEST'
export const ACTIVITY_RELATED_CREATE_SUCCESS = 'ACTIVITY_RELATED_CREATE_SUCCESS'
export const ACTIVITY_RELATED_CREATE_FAIL = 'ACTIVITY_RELATED_CREATE_FAIL'
export const ACTIVITY_RELATED_CREATE_RESET = 'ACTIVITY_RELATED_CREATE_RESET'

export const ACTIVITY_RELATED_UPDATE_REQUEST = 'ACTIVITY_RELATED_UPDATE_REQUEST'
export const ACTIVITY_RELATED_UPDATE_SUCCESS = 'ACTIVITY_RELATED_UPDATE_SUCCESS'
export const ACTIVITY_RELATED_UPDATE_FAIL = 'ACTIVITY_RELATED_UPDATE_FAIL'
export const ACTIVITY_RELATED_UPDATE_RESET = 'ACTIVITY_RELATED_UPDATE_RESET'

export const ACTIVITY_RELATED_LIST_OPTION_REQUEST = 'ACTIVITY_RELATED_LIST_OPTION_REQUEST'
export const ACTIVITY_RELATED_LIST_OPTION_SUCCESS = 'ACTIVITY_RELATED_LIST_OPTION_SUCCESS'
export const ACTIVITY_RELATED_LIST_OPTION_FAIL = 'ACTIVITY_RELATED_LIST_OPTION_FAIL'
export const ACTIVITY_RELATED_LIST_OPTION_RESET = 'ACTIVITY_RELATED_LIST_OPTION_RESET'




