export const ACTIVITY_RELATED_LIST_REQUEST = 'ACTIVITY_RELATED_LIST_REQUEST'
export const ACTIVITY_RELATED_LIST_SUCCESS = 'ACTIVITY_RELATED_LIST_SUCCESS'
export const ACTIVITY_RELATED_LIST_FAIL = 'ACTIVITY_RELATED_LIST_FAIL'
export const ACTIVITY_RELATED_LIST_RESET = 'ACTIVITY_RELATED_LIST_RESET'