export const DECISION_LIST_REQUEST = 'DECISION_LIST_REQUEST'
export const DECISION_LIST_SUCCESS = 'DECISION_LIST_SUCCESS'
export const DECISION_LIST_FAIL = 'DECISION_LIST_FAIL'
export const DECISION_LIST_RESET = 'DECISION_LIST_RESET'

export const DECISION_CREATE_REQUEST = 'DECISION_CREATE_REQUEST'
export const DECISION_CREATE_SUCCESS = 'DECISION_CREATE_SUCCESS'
export const DECISION_CREATE_FAIL = 'DECISION_CREATE_FAIL'
export const DECISION_CREATE_RESET = 'DECISION_CREATE_RESET'

export const DECISION_UPDATE_REQUEST = 'DECISION_UPDATE_REQUEST'
export const DECISION_UPDATE_SUCCESS = 'DECISION_UPDATE_SUCCESS'
export const DECISION_UPDATE_FAIL = 'DECISION_UPDATE_FAIL'
export const DECISION_UPDATE_RESET = 'DECISION_UPDATE_RESET'

export const DECISION_DETAILS_REQUEST = 'DECISION_DETAILS_REQUEST'
export const DECISION_DETAILS_SUCCESS = 'DECISION_DETAILS_SUCCESS'
export const DECISION_DETAILS_FAIL = 'DECISION_DETAILS_FAIL'
export const DECISION_DETAILS_RESET = 'DECISION_DETAILS_RESET'

export const DECISION_DELETE_REQUEST = 'DECISION_DELETE_REQUEST'
export const DECISION_DELETE_SUCCESS = 'DECISION_DELETE_SUCCESS'
export const DECISION_DELETE_FAIL = 'DECISION_DELETE_FAIL'

