export const DESTINATION_LIST_REQUEST = 'DESTINATION_LIST_REQUEST'
export const DESTINATION_LIST_SUCCESS = 'DESTINATION_LIST_SUCCESS'
export const DESTINATION_LIST_FAIL = 'DESTINATION_LIST_FAIL'
export const DESTINATION_LIST_RESET = 'DESTINATION_LIST_RESET'

export const DESTINATION_CREATE_REQUEST = 'DESTINATION_CREATE_REQUEST'
export const DESTINATION_CREATE_SUCCESS = 'DESTINATION_CREATE_SUCCESS'
export const DESTINATION_CREATE_FAIL = 'DESTINATION_CREATE_FAIL'
export const DESTINATION_CREATE_RESET = 'DESTINATION_CREATE_RESET'

export const DESTINATION_DETAILS_REQUEST = 'DESTINATION_DETAILS_REQUEST'
export const DESTINATION_DETAILS_SUCCESS = 'DESTINATION_DETAILS_SUCCESS'
export const DESTINATION_DETAILS_FAIL = 'DESTINATION_DETAILS_FAIL'
export const DESTINATION_DETAILS_RESET = 'DESTINATION_DETAILS_RESET'

export const DESTINATION_DELETE_REQUEST = 'DESTINATION_DELETE_REQUEST'
export const DESTINATION_DELETE_SUCCESS = 'DESTINATION_DELETE_SUCCESS'
export const DESTINATION_DELETE_FAIL = 'DESTINATION_DELETE_FAIL'

export const DESTINATION_UPDATE_REQUEST = 'DESTINATION_UPDATE_REQUEST'
export const DESTINATION_UPDATE_SUCCESS = 'DESTINATION_UPDATE_SUCCESS'
export const DESTINATION_UPDATE_FAIL = 'DESTINATION_UPDATE_FAIL'
export const DESTINATION_UPDATE_RESET = 'DESTINATION_UPDATE_RESET'

export const DESTINATION_LIST_OPTION_REQUEST = 'DESTINATION_LIST_OPTION_REQUEST'
export const DESTINATION_LIST_OPTION_SUCCESS = 'DESTINATION_LIST_OPTION_SUCCESS'
export const DESTINATION_LIST_OPTION_FAIL = 'DESTINATION_LIST_OPTION_FAIL'
export const DESTINATION_LIST_OPTION_RESET = 'DESTINATION_LIST_OPTION_RESET'