export const DESTINATION_LIST_REQUEST = 'DESTINATION_LIST_REQUEST'
export const DESTINATION_LIST_SUCCESS = 'DESTINATION_LIST_SUCCESS'
export const DESTINATION_LIST_FAIL = 'DESTINATION_LIST_FAIL'
export const DESTINATION_LIST_RESET = 'DESTINATION_LIST_RESET'

export const DESTINATION_CREATE_REQUEST = 'DESTINATION_CREATE_REQUEST'
export const DESTINATION_CREATE_SUCCESS = 'DESTINATION_CREATE_SUCCESS'
export const DESTINATION_CREATE_FAIL = 'DESTINATION_CREATE_FAIL'
export const DESTINATION_CREATE_RESET = 'DESTINATION_CREATE_RESET'