export const INVENTORY_CREATE_REQUEST = 'INVENTORY_CREATE_REQUEST'
export const INVENTORY_CREATE_SUCCESS = 'INVENTORY_CREATE_SUCCESS'
export const INVENTORY_CREATE_FAIL = 'INVENTORY_CREATE_FAIL'
export const INVENTORY_CREATE_RESET = 'INVENTORY_CREATE_RESET'