export const INVENTORY_CREATE_REQUEST = 'INVENTORY_CREATE_REQUEST'
export const INVENTORY_CREATE_SUCCESS = 'INVENTORY_CREATE_SUCCESS'
export const INVENTORY_CREATE_FAIL = 'INVENTORY_CREATE_FAIL'
export const INVENTORY_CREATE_RESET = 'INVENTORY_CREATE_RESET'

export const INVENTORY_CREATE_BULK_REQUEST = 'INVENTORY_CREATE_BULK_REQUEST'
export const INVENTORY_CREATE_BULK_SUCCESS = 'INVENTORY_CREATE_BULK_SUCCESS'
export const INVENTORY_CREATE_BULK_FAIL = 'INVENTORY_CREATE_BULK_FAIL'
export const INVENTORY_CREATE_BULK_RESET = 'INVENTORY_CREATE_BULK_RESET'