export const CALENDAR_SCHEDULE_LIST_REQUEST = 'CALENDAR_SCHEDULE_LIST_REQUEST'
export const CALENDAR_SCHEDULE_LIST_SUCCESS = 'CALENDAR_SCHEDULE_LIST_SUCCESS'
export const CALENDAR_SCHEDULE_LIST_FAIL = 'CALENDAR_SCHEDULE_LIST_FAIL'
export const CALENDAR_SCHEDULE_LIST_RESET = 'CALENDAR_SCHEDULE_LIST_RESET'

export const CALENDAR_SCHEDULE_CREATE_REQUEST = 'CALENDAR_SCHEDULE_CREATE_REQUEST'
export const CALENDAR_SCHEDULE_CREATE_SUCCESS = 'CALENDAR_SCHEDULE_CREATE_SUCCESS'
export const CALENDAR_SCHEDULE_CREATE_FAIL = 'CALENDAR_SCHEDULE_CREATE_FAIL'
export const CALENDAR_SCHEDULE_CREATE_RESET = 'CALENDAR_SCHEDULE_CREATE_RESET'

export const CALENDAR_SCHEDULE_DETAILS_REQUEST = 'CALENDAR_SCHEDULE_DETAILS_REQUEST'
export const CALENDAR_SCHEDULE_DETAILS_SUCCESS = 'CALENDAR_SCHEDULE_DETAILS_SUCCESS'
export const CALENDAR_SCHEDULE_DETAILS_FAIL = 'CALENDAR_SCHEDULE_DETAILS_FAIL'
export const CALENDAR_SCHEDULE_DETAILS_RESET = 'CALENDAR_SCHEDULE_DETAILS_RESET'

export const CALENDAR_SCHEDULE_UPDATE_REQUEST = 'CALENDAR_SCHEDULE_UPDATE_REQUEST'
export const CALENDAR_SCHEDULE_UPDATE_SUCCESS = 'CALENDAR_SCHEDULE_UPDATE_SUCCESS'
export const CALENDAR_SCHEDULE_UPDATE_FAIL = 'CALENDAR_SCHEDULE_UPDATE_FAIL'
export const CALENDAR_SCHEDULE_UPDATE_RESET = 'CALENDAR_SCHEDULE_UPDATE_RESET'