export const BUSINESS_UNIT_LIST_REQUEST = 'BUSINESS_UNIT_LIST_REQUEST'
export const BUSINESS_UNIT_LIST_SUCCESS = 'BUSINESS_UNIT_LIST_SUCCESS'
export const BUSINESS_UNIT_LIST_FAIL = 'BUSINESS_UNIT_LIST_FAIL'
export const BUSINESS_UNIT_LIST_RESET = 'BUSINESS_UNIT_LIST_RESET'