export const BUSINESS_UNIT_LIST_REQUEST = 'BUSINESS_UNIT_LIST_REQUEST'
export const BUSINESS_UNIT_LIST_SUCCESS = 'BUSINESS_UNIT_LIST_SUCCESS'
export const BUSINESS_UNIT_LIST_FAIL = 'BUSINESS_UNIT_LIST_FAIL'
export const BUSINESS_UNIT_LIST_RESET = 'BUSINESS_UNIT_LIST_RESET'

export const BUSINESS_UNIT_LIST_OPTION_REQUEST = 'BUSINESS_UNIT_LIST_OPTION_REQUEST'
export const BUSINESS_UNIT_LIST_OPTION_SUCCESS = 'BUSINESS_UNIT_LIST_OPTION_SUCCESS'
export const BUSINESS_UNIT_LIST_OPTION_FAIL = 'BUSINESS_UNIT_LIST_OPTION_FAIL'
export const BUSINESS_UNIT_LIST_OPTION_RESET = 'BUSINESS_UNIT_LIST_OPTION_RESET'
