export const BUSINESS_UNIT_LIST_REQUEST = 'BUSINESS_UNIT_LIST_REQUEST'
export const BUSINESS_UNIT_LIST_SUCCESS = 'BUSINESS_UNIT_LIST_SUCCESS'
export const BUSINESS_UNIT_LIST_FAIL = 'BUSINESS_UNIT_LIST_FAIL'
export const BUSINESS_UNIT_LIST_RESET = 'BUSINESS_UNIT_LIST_RESET'

export const BUSINESS_UNIT_DETAILS_REQUEST = 'BUSINESS_UNIT_DETAILS_REQUEST'
export const BUSINESS_UNIT_DETAILS_SUCCESS = 'BUSINESS_UNIT_DETAILS_SUCCESS'
export const BUSINESS_UNIT_DETAILS_FAIL = 'BUSINESS_UNIT_DETAILS_FAIL'
export const BUSINESS_UNIT_DETAILS_RESET = 'BUSINESS_UNIT_DETAILS_RESET'

export const BUSINESS_UNIT_LIST_OPTION_REQUEST = 'BUSINESS_UNIT_LIST_OPTION_REQUEST'
export const BUSINESS_UNIT_LIST_OPTION_SUCCESS = 'BUSINESS_UNIT_LIST_OPTION_SUCCESS'
export const BUSINESS_UNIT_LIST_OPTION_FAIL = 'BUSINESS_UNIT_LIST_OPTION_FAIL'
export const BUSINESS_UNIT_LIST_OPTION_RESET = 'BUSINESS_UNIT_LIST_OPTION_RESET'

export const BUSINESS_UNIT_CREATE_REQUEST = 'BUSINESS_UNIT_CREATE_REQUEST'
export const BUSINESS_UNIT_CREATE_SUCCESS = 'BUSINESS_UNIT_CREATE_SUCCESS'
export const BUSINESS_UNIT_CREATE_FAIL = 'BUSINESS_UNIT_CREATE_FAIL'
export const BUSINESS_UNIT_CREATE_RESET = 'BUSINESS_UNIT_CREATE_RESET'

export const BUSINESS_UNIT_UPDATE_REQUEST = 'BUSINESS_UNIT_UPDATE_REQUEST'
export const BUSINESS_UNIT_UPDATE_SUCCESS = 'BUSINESS_UNIT_UPDATE_SUCCESS'
export const BUSINESS_UNIT_UPDATE_FAIL = 'BUSINESS_UNIT_UPDATE_FAIL'
export const BUSINESS_UNIT_UPDATE_RESET = 'BUSINESS_UNIT_UPDATE_RESET'