export const MENU_CATEGORY_LIST_REQUEST = 'MENU_CATEGORY_LIST_REQUEST'
export const MENU_CATEGORY_LIST_SUCCESS = 'MENU_CATEGORY_LIST_SUCCESS'
export const MENU_CATEGORY_LIST_FAIL = 'MENU_CATEGORY_LIST_FAIL'
export const MENU_CATEGORY_LIST_RESET = 'MENU_CATEGORY_LIST_RESET'

export const MENU_CATEGORY_DETAILS_REQUEST = 'MENU_CATEGORY_DETAILS_REQUEST'
export const MENU_CATEGORY_DETAILS_SUCCESS = 'MENU_CATEGORY_DETAILS_SUCCESS'
export const MENU_CATEGORY_DETAILS_FAIL = 'MENU_CATEGORY_DETAILS_FAIL'
export const MENU_CATEGORY_DETAILS_RESET = 'MENU_CATEGORY_DETAILS_RESET'

export const MENU_CATEGORY_UPDATE_REQUEST = 'MENU_CATEGORY_UPDATE_REQUEST'
export const MENU_CATEGORY_UPDATE_SUCCESS = 'MENU_CATEGORY_UPDATE_SUCCESS'
export const MENU_CATEGORY_UPDATE_FAIL = 'MENU_CATEGORY_UPDATE_FAIL'
export const MENU_CATEGORY_UPDATE_RESET = 'MENU_CATEGORY_UPDATE_RESET'

export const MENU_CATEGORY_CREATE_REQUEST = 'MENU_CATEGORY_CREATE_REQUEST'
export const MENU_CATEGORY_CREATE_SUCCESS = 'MENU_CATEGORY_CREATE_SUCCESS'
export const MENU_CATEGORY_CREATE_FAIL = 'MENU_CATEGORY_CREATE_FAIL'
export const MENU_CATEGORY_CREATE_RESET = 'MENU_CATEGORY_CREATE_RESET'

