export const SUB_CATEGORY_LIST_REQUEST = 'SUB_CATEGORY_LIST_REQUEST'
export const SUB_CATEGORY_LIST_SUCCESS = 'SUB_CATEGORY_LIST_SUCCESS'
export const SUB_CATEGORY_LIST_FAIL = 'SUB_CATEGORY_LIST_FAIL'
export const SUB_CATEGORY_LIST_RESET = 'SUB_CATEGORY_LIST_RESET'

export const SUB_CATEGORY_DETAILS_REQUEST = 'SUB_CATEGORY_DETAILS_REQUEST'
export const SUB_CATEGORY_DETAILS_SUCCESS = 'SUB_CATEGORY_DETAILS_SUCCESS'
export const SUB_CATEGORY_DETAILS_FAIL = 'SUB_CATEGORY_DETAILS_FAIL'
export const SUB_CATEGORY_DETAILS_RESET = 'SUB_CATEGORY_DETAILS_RESET'

export const SUB_CATEGORY_UPDATE_REQUEST = 'SUB_CATEGORY_UPDATE_REQUEST'
export const SUB_CATEGORY_UPDATE_SUCCESS = 'SUB_CATEGORY_UPDATE_SUCCESS'
export const SUB_CATEGORY_UPDATE_FAIL = 'SUB_CATEGORY_UPDATE_FAIL'
export const SUB_CATEGORY_UPDATE_RESET = 'SUB_CATEGORY_UPDATE_RESET'