export const ROLE_LIST_REQUEST = 'ROLE_LIST_REQUEST'
export const ROLE_LIST_SUCCESS = 'ROLE_LIST_SUCCESS'
export const ROLE_LIST_FAIL = 'ROLE_LIST_FAIL'
export const ROLE_LIST_RESET = 'ROLE_LIST_RESET'

export const ROLE_DETAILS_REQUEST = 'ROLE_DETAILS_REQUEST'
export const ROLE_DETAILS_SUCCESS = 'ROLE_DETAILS_SUCCESS'
export const ROLE_DETAILS_FAIL = 'ROLE_DETAILS_FAIL'
export const ROLE_DETAILS_RESET = 'ROLE_DETAILS_RESET'
