export const CASE_LIST_REQUEST = 'CASE_LIST_REQUEST'
export const CASE_LIST_SUCCESS = 'CASE_LIST_SUCCESS'
export const CASE_LIST_FAIL = 'CASE_LIST_FAIL'
export const CASE_LIST_RESET = 'CASE_LIST_RESET'